#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by Selenium IDE
from time import sleep

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

"""
Selenium IDE 录制的代码：
1、代码冗余
2、还需要添加断言
"""


class TestDemo1():
    def setup_method(self, method):
        option = Options()
        option.debugger_address = "localhost:9222"
        self.driver = webdriver.Chrome(options=option)
        # 隐式等待
        self.driver.implicitly_wait(5)

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo1(self):
        # self.driver.get("https://ceshiren.com/")
        self.driver.set_window_size(1536, 960)
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        # 断言
        myclass = self.driver.find_element(By.LINK_TEXT, "所有分类").get_attribute("class")
        assert "active" == myclass
        sleep(3)
